uploads = []
outputs = []

[[generated]]
id = "hlKAzZ65xI_Rb_do3QHo1"
uri = "file://public/twh-hero-bg.png"
type = "image"
title = "twh cinematic hero background"

[[generated]]
id = "Ji3BKdnNuMkxOeGr_fbg7"
uri = "file://public/afsar-avatar.png"
type = "image"
title = "afsar ali hacker avatar"
